{ config, lib, pkgs, modulesPath, ... }:

# Placeholder. This file is auto-generated by `nixos-generate-config` on the
# physical host during Phase 2 (Task 2.1) and must be replaced with the real
# output before running `nixos-rebuild switch`. Do not hand-edit the real
# generated version beyond what NixOS documentation recommends.
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  swapDevices = [ ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault true;
}
